{
  config,
  lib,
  ...
}:
let
  dotfilesDir = "${config.home.homeDirectory}/ghq/github.com/${config.home.username}/dotfiles";
in
{
  # home-manager switch のたびに dotfiles リポジトリへ git hook を設置する。
  # devShell / direnv に依存せず、switch を実行するだけで配線される。
  home.activation.installGitHooks = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    DOTFILES_DIR="${dotfilesDir}"
    if [ -d "$DOTFILES_DIR/.git" ]; then
      mkdir -p "$DOTFILES_DIR/.git/hooks"

      # staged ファイルに treefmt を適用する自動修正型 pre-commit。
      cat > "$DOTFILES_DIR/.git/hooks/pre-commit" << 'HOOK_EOF'
    #!/usr/bin/env bash
    # Generated by home-manager/cli/git/git-hooks.nix
    # コミット前に staged ファイルへ treefmt を適用する

    STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR)
    if [ -z "$STAGED_FILES" ]; then
      exit 0
    fi

    echo "Running treefmt on staged files..."

    # unstaged 変更を退避し、treefmt が staged の内容だけを見るようにする。
    # 無関係なファイルを巻き込んで stage するのを防ぐ。
    STASH_NEEDED=false
    if ! git diff --quiet || [ -n "$(git ls-files --others --exclude-standard)" ]; then
      git stash --quiet --keep-index --include-untracked
      STASH_NEEDED=true
    fi

    # treefmt を実行する。--fail-on-change は付けず、その場で整形して上書きする。
    treefmt_result=0
    nix run .#fmt 2>/dev/null || treefmt_result=$?

    # 整形で変わった可能性のある staged ファイルを再ステージする。
    for file in $STAGED_FILES; do
      if [ -f "$file" ]; then
        git add "$file"
      fi
    done

    # 退避した変更を戻す。
    if [ "$STASH_NEEDED" = true ]; then
      git stash pop --quiet
    fi

    if [ $treefmt_result -ne 0 ]; then
      echo "treefmt failed"
      exit 1
    fi

    exit 0
    HOOK_EOF
      chmod +x "$DOTFILES_DIR/.git/hooks/pre-commit"

      echo "Git hooks installed successfully!"
    fi
  '';
}
