source = ~/.config/hypr/colors.conf

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 6
    contrast = 0.9
    brightness = 0.75
    vibrancy = 0.17
    vibrancy_darkness = 0.0
}

general {
    hide_cursor = false
    ignore_empty_input = true
}

animations {
    enabled = true
    animation = fadeOut, 1, 1, linear
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = $primary_a95
    font_size = 120
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, 240
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %B %-d")"
    color = $primary_fixed_a80
    font_size = 28
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 110
    halign = center
    valign = center
}

image {
    monitor =
    path = ~/.face.icon
    border_color = $primary_container_a90
    border_size = 3
    size = 140
    rounding = -1
    rotate = 0
    reload_time = -1
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:3600000] echo "$(h=$(date +%H); if [ $h -lt 6 ]; then echo 'Good night'; elif [ $h -lt 12 ]; then echo 'Good morning'; elif [ $h -lt 18 ]; then echo 'Good afternoon'; else echo 'Good evening'; fi), $USER"
    color = $tertiary_a95
    font_size = 22
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, -150
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 60
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    dots_rounding = -1
    outer_color = $primary_container_a85
    inner_color = $surface_a75
    font_color = $on_surface
    fade_on_empty = false
    font_family = JetBrainsMono Nerd Font
    placeholder_text = <i>Enter password...</i>
    hide_input = false
    check_color = $state_success_a90
    fail_color = $state_critical_a90
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    position = 0, -230
    halign = center
    valign = center
}

label {
    monitor =
    text = Type to unlock
    color = $on_surface_a50
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    position = 0, -310
    halign = center
    valign = center
}
