source = ~/.config/hypr/appearance/general.conf
source = ~/.config/hypr/appearance/decoration.conf
source = ~/.config/hypr/appearance/animations.conf
source = ~/.config/hypr/appearance/dwindle.conf
source = ~/.config/hypr/appearance/misc.conf
