exec-once = uwsm app -- fcitx5 -d --replace
exec-once = uwsm app -- waybar
exec-once = uwsm app -- hypridle
exec-once = uwsm app -- elephant
exec-once = uwsm app -- walker --gapplication-service
exec-once = uwsm app -- $HOME/.config/hypr/scripts/wallset-backend-startup.sh
exec-once = uwsm app -- $HOME/.config/hypr/scripts/wallset-rotate-loop.sh
