[General]
ScreenWidth="2560"
ScreenHeight="1440"
ScreenPadding=""
Font="Open Sans"
FontSize=""
KeyboardSize="0.4"
RoundCorners="20"
Locale="en_US"
HourFormat="HH:mm"
DateFormat="dddd, MMMM d"
HeaderText=""

BackgroundPlaceholder=""
Background="Backgrounds/login.png"
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.3"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

HeaderTextColor="{{colors.on_surface.default.hex}}"
DateTextColor="{{colors.on_surface.default.hex}}"
TimeTextColor="{{colors.on_surface.default.hex}}"

FormBackgroundColor="{{colors.surface.default.hex}}"
BackgroundColor="{{colors.surface.default.hex}}"
DimBackgroundColor="{{colors.surface.default.hex}}"

LoginFieldBackgroundColor="{{colors.surface_container_high.default.hex}}"
PasswordFieldBackgroundColor="{{colors.surface_container_high.default.hex}}"
LoginFieldTextColor="{{colors.on_surface.default.hex}}"
PasswordFieldTextColor="{{colors.on_surface.default.hex}}"
UserIconColor="{{colors.on_surface.default.hex}}"
PasswordIconColor="{{colors.on_surface.default.hex}}"

PlaceholderTextColor="{{colors.on_surface_variant.default.hex}}"
WarningColor="{{colors.error.default.hex}}"

LoginButtonTextColor="{{colors.on_primary.default.hex}}"
LoginButtonBackgroundColor="{{colors.primary.default.hex}}"
SystemButtonsIconsColor="{{colors.on_surface.default.hex}}"
SessionButtonTextColor="{{colors.on_surface.default.hex}}"
VirtualKeyboardButtonTextColor="{{colors.on_surface.default.hex}}"

DropdownTextColor="{{colors.on_surface.default.hex}}"
DropdownSelectedBackgroundColor="{{colors.primary_container.default.hex}}"
DropdownBackgroundColor="{{colors.surface_container.default.hex}}"

HighlightTextColor="{{colors.on_primary_container.default.hex}}"
HighlightBackgroundColor="{{colors.primary_container.default.hex}}"
HighlightBorderColor="{{colors.primary.default.hex}}"

HoverUserIconColor="{{colors.primary.default.hex}}"
HoverPasswordIconColor="{{colors.primary.default.hex}}"
HoverSystemButtonsIconsColor="{{colors.primary.default.hex}}"
HoverSessionButtonTextColor="{{colors.primary.default.hex}}"
HoverVirtualKeyboardButtonTextColor="{{colors.primary.default.hex}}"

PartialBlur="false"
FullBlur=""
BlurMax=""
Blur=""

HaveFormBackground="false"
FormPosition="center"

VirtualKeyboardPosition="center"

HideVirtualKeyboard="true"
HideSystemButtons="false"
HideLoginButton="false"

UseRealName="true"
ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
