[config]
default_mode = "dark"

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar-colors.css"
output_path = "~/.config/waybar/colors.css"

[templates.wlogout]
input_path = "~/.config/matugen/templates/wlogout-colors.css"
output_path = "~/.config/wlogout/colors.css"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/hypr/colors.conf"

[templates.walker]
input_path = "~/.config/matugen/templates/walker-colors.css"
output_path = "~/.config/walker/themes/matugen/colors.css"

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi-colors.rasi"
output_path = "~/.config/rofi/themes/colors-matugen.rasi"

[templates.quickshell]
input_path = "~/.config/matugen/templates/quickshell-colors.json"
output_path = "~/.cache/quickshell/matugen-colors.json"
