[config]
default_mode = "dark"

[templates.wlogout]
input_path = "~/.config/matugen/templates/wlogout-colors.css"
output_path = "~/.config/wlogout/colors.css"

[templates.hyprland_lua]
input_path = "~/.config/matugen/templates/hyprland-colors.lua"
output_path = "~/.config/hypr/colors.lua"

[templates.quickshell]
input_path = "~/.config/matugen/templates/quickshell-colors.json"
output_path = "~/.cache/quickshell/matugen-colors.json"
post_hook = "qs -c shell ipc call theme reload 2>/dev/null; true"

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi-colors.rasi"
output_path = "~/.config/rofi/themes/colors.rasi"
