source = ~/.config/hypr/lock-colors.conf

$font = JetBrainsMono Nerd Font

general {
    grace = 0
    hide_cursor = true
    immediate_render = true
}

background {
    monitor =
    path = ~/.config/hypr/lock.jpg
}

# Password
input-field {
    monitor =
    size = 250, 80
    outline_thickness = 2
    dots_size = 0.30
    dots_spacing = 0.2
    dots_center = true
    rounding = 6
    outer_color = $lock_surface
    inner_color = $lock_bg
    font_color = $lock_text
    fade_on_empty = true
    placeholder_text = <i>Hi, $USER</i>
    position = 170, 180
    halign = left
    valign = bottom
}

# Hour
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%H") </big></b>"
    color = $lock_primary
    font_size = 120
    font_family = $font
    position = 100, 100
    halign = left
    valign = center
}

# Minute
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%M") </big></b>"
    color = $lock_text
    font_size = 120
    font_family = $font
    position = 100, 240
    halign = left
    valign = bottom
}
