$lock_accent = rgba({{color13 | strip}}ff)
$lock_rule = rgba({{foreground | strip}}33)
$lock_date = rgba({{foreground | strip}}cc)
$lock_input_text = rgba({{foreground | strip}}ff)
$lock_fail = rgba({{color1 | strip}}ff)
